# Generated by Django 2.2 on 2024-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ssddff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
